services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "${MSSQL_HOST_PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 5s
      retries: 5

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssql_tools
    depends_on:
      mssql:
        condition: service_healthy
    entrypoint: >
      /bin/bash -c "
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P ${MSSQL_SA_PASSWORD} -d master -Q \"
        CREATE DATABASE ${MSSQL_DATABASE};
        GO
        CREATE LOGIN ${MSSQL_USER} WITH PASSWORD = '${MSSQL_PASSWORD}';
        GO
        USE ${MSSQL_DATABASE};
        GO
        CREATE USER ${MSSQL_USER} FOR LOGIN ${MSSQL_USER};
        GO
        ALTER ROLE db_owner ADD MEMBER ${MSSQL_USER};
        GO
      \"
      " 

volumes:
  mssql_data:
