services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backengin:
    build: .
    image: enginar-backend
    container_name: backengin
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8090:8080"
volumes:
  postgres_data:
