services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    restart: always
  
  enginar-frontend:
    image: tamerkucukel/enginar-frontend:latest
    ports:
      - "3000:80"